# Generated by Django 4.2.1 on 2023-05-28 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ua_phone_number",
                    models.PositiveIntegerField(
                        help_text="numbers starts after `+380`",
                        unique=True,
                        verbose_name="UA phone number",
                    ),
                ),
                ("session", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ua_phone_number"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROR", "pre-order"),
                            ("INIT", "initialized"),
                            ("DELV", "delivering"),
                            ("FULF", "fulfilled"),
                            ("CNCL", "canceled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="menu.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["publication_date"],
            },
        ),
        migrations.CreateModel(
            name="RepresentationFilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("price_UAH", models.FloatField()),
            ],
            options={
                "ordering": ["pk", "name"],
            },
        ),
        migrations.CreateModel(
            name="PizzaKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image_http_url",
                    models.URLField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="HTTP URL to image",
                    ),
                ),
                ("description", models.TextField(max_length=6000)),
                (
                    "representation_filling",
                    models.ManyToManyField(to="menu.representationfilling"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_cm",
                    models.PositiveSmallIntegerField(choices=[(30, "30"), (50, "50")]),
                ),
                ("weight_grams", models.PositiveSmallIntegerField()),
                ("price_UAH", models.FloatField()),
                (
                    "pizza_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pizzas",
                        to="menu.pizzakind",
                    ),
                ),
            ],
            options={
                "ordering": ["size_cm"],
            },
        ),
        migrations.CreateModel(
            name="OrderPizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveSmallIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_pizzas",
                        to="menu.order",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to="menu.pizza",
                    ),
                ),
                (
                    "toppings",
                    models.ManyToManyField(
                        blank=True, related_name="order_pizzas", to="menu.topping"
                    ),
                ),
            ],
            options={
                "ordering": ["amount"],
            },
        ),
    ]
